apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: mynginxpods
  template:
    metadata:
      labels:
        app: mynginxpods
    spec:
      containers:
        - name: mynginxcontainer
          image: nginx
          ports:
            - containerPort: 80
